spring:
  data:
    mongodb:
      database: ${MONGO_DB}
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_CLUSTER}/test
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ACCOUNT}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          ssl:
          auth: true
          starttls:
            enable: true